### ISSUE TITLE
Package should include a script to execute the code.

### ISSUE THREAD

**Issue by ckloote** [GlobalNOC/routeflow-bgp-analysis#3]
We need some sort of actual wrapper script to run the library. Should take as arguments the config file location and a start and end date and be installed as part of the package.

**Comment by mihirthatte** [comment]
I have added a shell command to run the python script. 
The script can be started by executing the command - 
```bgp-report-run [START_TIME] [END_TIME] [path to config.json file]```

Example command - 
```bgp-report-run 2017-11-15-16-58-39 2017-11-15-17-19-39 /home/mthatte```
